default:
  outputs:

    dev:
      type: postgres
      threads: 5
      host: database-qa-master.coqeiusw8svd.us-west-2.rds.amazonaws.com
      port: 5432
      user: postgres
      pass: Elucidate123
      dbname: cloud_services
      schema: stripe_test

    # prod:
    #   type: redshift
    #   method: iam
    #   cluster_id: [cluster_id]
    #   threads: [1 or more]
    #   host: [host]
    #   port: [port]
    #   user: [prod_user]
    #   dbname: [dbname]
    #   schema: [prod_schema]

  target: dev

